### ISSUE TITLE
[Future Request]: QCN on Linux 64-Bit

### ISSUE THREAD

**Issue by visious25** [carlgt1/qcn#1]
Hi, could you please build an environment for Quake Catcher Network on Linux 64-Bit in the future?

**Comment by ch3p4ll3** [comment]
Hi, unfortunately the Quake-Catcher network was discontinued on June 1, 2023. so I don't think there is any will on the part of the developer to maintain the software (taking into account that the last commit was in 2018). Fortunately, however, there is good documentation
